import { Redirects } from "./theme";

// Alphabetical order please :)
export default {
  "/blocks/block-materials": "/blocks/block-components#render-methods",
  "/blocks/blocks-16": "/blocks/blocks-intro",
  "/blocks/blocks-stable": "/blocks/blocks-intro",
  "/blocks/custom-trapdoor": "/blocks/custom-trapdoors",

  "/commands/nbt-commands": "/commands/giving-nbt-items",
  "/commands/tellraw": "/text/rawtext",

  "/concepts/animation-controllers": "/animation-controllers/animation-controllers-intro",
  "/concepts/biomes": "/world-generation/biomes",
  "/concepts/blocks": "/blocks/blocks-intro",
  "/concepts/components-events-groups": "/entities/entity-intro-bp",
  "/concepts/emojis": "/text/emojis",
  "/concepts/entity-properties": "/entities/entity-properties",
  "/concepts/items": "/items/item-components",
  "/concepts/json-ui": "/json-ui/json-ui-intro",
  "/concepts/math-based-animations": "/visuals/math-based-animations",
  "/concepts/mcfunction": "/commands/mcfunction",
  "/concepts/rawtext": "/text/rawtext",
  "/concepts/render-controller": "/visuals/render-controller",
  "/concepts/text-and-translations": "/text/text-intro",

  "/documentation/biome-tags": "/world-generation/biome-tags",
  "/documentation/block-model-materials": "/blocks/block-components#render-methods",
  "/documentation/block-shapes": "/blocks/block-shapes",
  "/documentation/block-tags": "/blocks/block-tags",
  "/documentation/creative-categories": "/documentation/menu-categories",
  "/documentation/dummy-components": "/entities/dummy-components",
  "/documentation/emojis": "/text/emojis",
  "/documentation/item-groups": "/items/item-groups",
  "/documentation/json-ui": "/json-ui/json-ui-documentation",
  "/documentation/projectiles": "/entities/projectiles",
  "/documentation/runtime-identifier": "/entities/runtime-identifier",
  "/documentation/subpacks": "/concepts/subpacks",
  "/documentation/tellraw": "/text/rawtext",

  "/entities/entities-intro": "/entities/entity-intro-bp",
  "/entities/npc-dialogs": "/entities/npc-dialogue",

  "/items/3d-items": "/items/attachables",
  "/items/custom-pottery-sherd": "/items/custom-pottery-sherds",
  "/items/item-categories": "/documentation/menu-categories",

  "/json-ui/custom-buttons": "/json-ui/buttons-and-toggles",

  "/knowledge/addon-performance": "/meta/addon-performance",
  "/knowledge/addon-programming": "/meta/addon-programming",
  "/knowledge/bedrock-modeling": "/visuals/bedrock-modeling",
  "/knowledge/entity-movement": "/entities/entity-movement",
  "/knowledge/nbt_commands": "/commands/giving-nbt-items",
  "/knowledge/style-guide": "/meta/style-guide",
  "/knowledge/useful-links": "/meta/useful-links",
  "/knowledge/using-schemas": "/meta/using-schemas",
  "/knowledge/version-control": "/meta/version-control",

  "/scripting/custom-command": "/scripting/custom-commands",
  "/scripting/gametest-qna": "/meta/gametest-qna",
  "/scripting/scripting-editor-qna": "/meta/scripting-editor-qna",
  "/scripting/starting-scripts": "/scripting/scripting-intro",

  "/troubleshooting/entities": "/entities/troubleshooting-entities",
  "/troubleshooting/items": "/items/troubleshooting-items",

  "/tutorials/beginner-commands": "/commands/commands-intro",
  "/tutorials/block-texture-variation": "/blocks/block-texture-variation",
  "/tutorials/boat-entities": "/entities/boat-entities",
  "/tutorials/cancelling-death-animation": "/entities/cancelling-death-animation",
  "/tutorials/controlling-flying-entities": "/entities/flying-entities",
  "/tutorials/craftable-spawneggs": "/loot/craftable-spawneggs",
  "/tutorials/custom-armor": "/entities/custom-armor",
  "/tutorials/disabling-particles": "/visuals/disabling-particles",
  "/tutorials/disabling-team-damage": "/entities/disabling-team-damage",
  "/tutorials/egg-drops": "/loot/egg-drops",
  "/tutorials/entity-commands": "/commands/animation-controllers",
  "/tutorials/entity-events": "/entities/entity-events",
  "/tutorials/entity-holds-item": "/entities/entity-holds-item",
  "/tutorials/fake_blocks": "/blocks/fake-blocks",
  "/tutorials/invulnerable-entities": "/entities/invulnerable-entities",
  "/tutorials/item-models": "/items/attachables",
  "/tutorials/npc-dialogs": "/entities/npc-dialogue",
  "/tutorials/pathfinding-entities": "/entities/pathfinding-entities",
  "/tutorials/player-geometry": "/visuals/player-geometry",
  "/tutorials/remove-shadows": "/visuals/remove-shadows",
  "/tutorials/respawn-commands": "/commands/respawn-commands",
  "/tutorials/retexturing-spawn-eggs": "/visuals/retexturing-spawn-eggs",
  "/tutorials/solid-entities": "/entities/solid-entities",
  "/tutorials/spawning-items": "/items/spawning-items",
  "/tutorials/text-localization": "/concepts/text-localization",
  "/tutorials/timers": "/entities/timers",

  "/vanilla-usage/items": "/items/vanilla-usage-items",
  "/vanilla-usage/components": "/entities/vanilla-usage-components",
  "/vanilla-usage/spawn-rules": "/entities/vanilla-usage-spawn-rules",

  "/visuals/deferred-qna": "/meta/deferred-qna",
  "/visuals/entity-visuals-intro": "/entities/render-controllers",
  "/visuals/render-controllers": "/entities/render-controllers",

  "/world-generation/randomized-structure-loot": "/loot/randomized-structure-loot",
} satisfies Redirects;
