name: Deploy
on:
    push:
        branches:
            - wiki

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy 🚀
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  submodules: true

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  cache: npm
                  cache-dependency-path: package-lock.json
                  node-version-file: .nvmrc

            - name: Install Project 🔧
              run: npm install

            - name: Check Linting 🔎
              run: npm run lint

            - name: Check Build 🔧
              run: npm run build

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.0
              with:
                  branch: generated
                  folder: docs/.vitepress/dist

            - name: Bully someone into fixing it
              if: ${{ failure() }}
              uses: Bedrock-OSS/discord-bully@v2.0.0
              with:
                  webhook: https://canary.discord.com/api/webhooks/${{ secrets.WEBHOOK_ID }}/${{ secrets.WEBHOOK_TOKEN }}
                  gifApiKey: ${{ secrets.GIF_API_KEY }}
                  failMessage: '%random% <:PE_PandaBonk:885395101877166110>'
                  failTitle: 'Wiki deployment failed!'
                  failAuthor: 'You messed up'
                  gifFailQuery: fail
                  successTitle: 'Wiki deployment succeeded!'
                  successMessage: '%random% <:PE_PandaInLove:885395799029194853>'
                  gifSuccessQuery: success
                  successAuthor: 'You did it'
                  failed: 'true'

            - name: Send a message if previous build failed
              if: ${{ success() }}
              uses: Bedrock-OSS/discord-bully@v2.0.0
              with:
                  webhook: https://canary.discord.com/api/webhooks/${{ secrets.WEBHOOK_ID }}/${{ secrets.WEBHOOK_TOKEN }}
                  gifApiKey: ${{ secrets.GIF_API_KEY }}
                  failMessage: '%random% <:PE_PandaBonk:885395101877166110>'
                  failTitle: 'Wiki deployment failed!'
                  failAuthor: 'You messed up'
                  gifFailQuery: fail
                  successTitle: 'Wiki deployment succeeded!'
                  successMessage: '%random% <:PE_PandaInLove:885395799029194853>'
                  gifSuccessQuery: success
                  successAuthor: 'You did it'
                  failed: 'false'
